config/routes.rb
CapitalMarket::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :entries

  root to: 'static_pages#home'

  match '/signup',   to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/consultants', to: 'static_pages#consultants'

end

app/models/entry.rb
# encoding: utf-8

# == Schema Information
#
# Table name: entries
#
#  id             :integer         not null, primary key
#  the_type       :string(255)
#  amount         :string(255)
#  period         :string(255)
#  interest_rates :string(255)
#  description    :text
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#


class Entry < ActiveRecord::Base
  attr_accessible :amount, :description, :interest_rates, :period, :the_type

  validates :the_type,  presence: true

  validates :amount, presence: true
  validates :period, presence: true

  validates :description, presence: true, length: { minimum: 50 }
end

app/models/user.rb
# encoding: utf-8

# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  investor        :boolean         default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :investor
  has_secure_password
  before_save :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/entries_controller.rb
# encoding: utf-8

class EntriesController < ApplicationController
  before_filter :sign_in_user, only: [:new, :create]

  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new(the_type: '股权')
  end

  def create
    @entry = Entry.new(params[:entry])
    if @entry.save
      flash['success'] = '信息发布成功！'
      redirect_to @entry
    else
      render 'new'
    end
  end

  def show
    @entry = Entry.find(params[:id])
  end

  private

    def sign_in_user
      unless signed_in?
        store_location
        flash['info'] = '请您先登录'
        redirect_to signin_path
      end
    end

end

app/controllers/sessions_controller.rb
# encoding: utf-8

class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      sign_in user
      flash[:success] = '您已成功登录'
      redirect_back_or user
    else
      flash.now[:error] = '邮箱或者密码错误'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = '您已成功注销'
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def consultants
  end
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
  before_filter :sign_in_user, only: [:edit, :update]
  before_filter :guest_user, only: [:new, :create]
  before_filter :correct_user, only: [:edit, :update]

  def new
    @user = User.new
    if params[:investor] == 'y'
      @user.investor = true
    else
      @user.investor = false
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash['success'] = '恭喜您注册成功！'
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def index
    @users = User.all
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = '资料已更新'
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def sign_in_user
      unless signed_in?
        store_location
        flash['info'] = '请您先登录'
        redirect_to signin_path
      end
    end

    def guest_user
      if signed_in?
        flash['warning'] = '您处在登录状态, 请您注销后再执行相关操作'
        redirect_to root_path
      end
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash['error'] = '您没有权限访问别人的资源'
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies[:remember_token] = user.remember_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  private

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end

    def clear_return_to
      session.delete(:return_to)
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/entries/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<%= f.label :the_type, '融资方式' %> &nbsp;
<%= f.radio_button :the_type, '股权' %> 股权 &nbsp;
<%= f.radio_button :the_type, '债券' %> 债券
<br/><br/>

<%= f.label :amount, '融资规模' %>
<%= f.text_field :amount, placeholder: '1500万' %>

<%= f.label :period, '融资期限' %>
<%= f.text_field :period, placeholder: '1年期' %>

<%= f.label :interest_rates, '年利率' %>
<%= f.text_field :interest_rates, placeholder: '20%' %>

<%= f.label :description, '详细描述' %>
<%= f.text_area :description %>

app/views/entries/index.html.erb
<%= provide(:title, "资金需求信息一览")%>

<br/><h1>资金需求信息一览</h1><br/>

<%= link_to('发布资金需求信息', new_entry_path, class: 'btn pull-right btn-success btn-large') %><br/><br/><br/>

<table class="table table-striped">
  <tr><th>融资类型</th><th>融资规模</th><th>融资期限</th><th>年利率</th><th>查看详情</th></tr>
  <% @entries.each do |entry| %>
  <tr><td><%= entry.the_type%></td><td><%= entry.amount %></td><td><%= entry.period %></td><td><%= entry.interest_rates %></td><td><%= link_to('详情', entry)%></td></tr>
  <% end %>
</table>

app/views/entries/new.html.erb
<% provide(:title, '发布资金需求信息') %>

<div class="row">
  <div class="span6 offset3">

    <br/><h1>发布资金需求信息</h1><br/><br/>

    <%= form_for(@entry) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "发布", class: "btn btn-large btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/entries/show.html.erb
<% provide(:title, '资金需求信息') %>

<div class="row">
  <div class="span6 offset3">

<br/><h1>资金需求信息</h1><br/><br/>

<table class="table table-striped">
  <tr><th>融资类型</th><td><%= @entry.the_type %></td></tr>
  <tr><th>融资规模</th><td><%= @entry.amount %></td></tr>
  <tr><th>融资期限</th><td><%= @entry.period %></td></tr>
  <tr><th>年利率</th><td><%= @entry.interest_rates %></td></tr>
</table>

<p><b>详细描述:</b></p>
<%= @entry.description %>

  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
<%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Designed and implemented by <a href="http://tylerlong.me/" target="_blank">Tyler Long</a>
  </small>
  <nav>
    <ul>
      <li>&copy2012 all rights reserved.</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container" style="width: auto;">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">富甲天下</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li><%= link_to('知名投资方一览', users_path) %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to('资金需求信息一览', entries_path) %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to('联络财务顾问', consultants_path) %></li>
          <li class="divider-vertical"></li>
        </ul>
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <% if signed_in? %>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.investor? ? "资本方":"企业方" %> 账户 <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "账户主页", current_user %></li>
                <li><%= link_to "修改资料", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "注销", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "登录", signin_path %></li>
          <% end %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div>
  </div><!-- /navbar-inner -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | 富甲天下</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<%= render 'layouts/flash', flash: flash %>
<%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/consultants.html.erb
<% provide(:title, '联络财务顾问') %>

<br/><h1>联络财务顾问</h1><br/><br/>

<table class="table table-striped">
  <tr><th>姓名</th><th>职务</th><th>擅长领域</th><th>办公电话</th><th>业务咨询邮箱</th></tr>
  <tr>
    <td>陈玮</td>
    <td>高级财务顾问</td>
    <td>擅长房地产借贷</td>
    <td>0755-82322836</td>
    <td>chenwei@fujiatianxia.com</td>
  </tr>
  <tr>
    <td>张洵</td>
    <td>高级财务顾问</td>
    <td>擅长股权投资</td>
    <td>0755-82322840</td>
    <td>zhangxun@fujiatianxia.com</td>
  </tr>
  <tr>
    <td>赵越</td>
    <td>财务顾问</td>
    <td>擅长小额借款</td>
    <td>0755-82322837</td>
    <td>zhaoyue@fujiatianxia.com</td>
  </tr>
  <tr>
    <td>王梦</td>
    <td>财务顾问</td>
    <td>擅长抵押贷款</td>
    <td>0755-82322839</td>
    <td>wangmeng@fujiatianxia.com</td>
  </tr>
  <tr>
    <td>刘春涛</td>
    <td>财务顾问</td>
    <td>擅长股权投资</td>
    <td>0755-82322838</td>
    <td>liuchuntao@fujiatianxia.com</td>
  </tr>
</table>

app/views/static_pages/home.html.erb
<%= provide(:title, "欢迎来到富甲天下！") %>
<div class="row">
  <div class="span4">
    <div class="hero-unit">
      <h1>找资金</h1>
      <p>小额借款，资产抵押，融资租赁，短期借款，股权融资，股权转让，大宗交易，资源转让，资产出售…….</p>
      <p>
        <%= link_to "马上注册!", signup_path, class: "btn btn-large btn-success" %>
      </p>
    </div>
  </div>
  <div class="span4">
    <div class="hero-unit">
      <h1>找项目</h1>
      <p>短期贷款，企业债券，信托贷款，抵押贷款，PE投资，资产收购，股权接收，资源收购，风险投资…….</p>
      <p>
        <%= link_to "马上注册!", signup_path(investor: 'y'), class: "btn btn-large btn-success" %>
      </p>
    </div>
  </div>
  <div class="span4">
    <div class="hero-unit">
      <h1>找顾问</h1>
      <p>为您找到最合适的投融资方式，提供一揽子借贷，资产抵押，股权转让，融资租赁，矿产转让，资产并购解决方案</p>
      <p>
        <%= link_to "联系顾问", consultants_path, class: "btn btn-large btn-success" %>
      </p>
    </div>
  </div>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<%= f.hidden_field :investor %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, "修改资料") %>

<div class="row">
  <div class="span6 offset3">

    <br/><h1>修改资料</h1><br/><br/>

    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "保存更改", :class => "btn btn-large btn-primary pull-right" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">换头像</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '知名资本方一览') %>

<br/><h1>知名资本方一览</h1><br/>

<%= link_to('注册成为资本方', signup_path(investor: 'y'), class: 'btn pull-right btn-success btn-large') %><br/><br/><br/>

<table class="table table-striped">
  <tr><th>形象照片</th><th>注册名称</th><th>资金规模</th><th>投资兴趣</th></tr>
  <% @users.each do |user| %>
  <tr><td><%= gravatar_for user, size: 64 %></td><td><%= user.name %></td><td>10亿</td><td>抵押贷款/PE投资/资产收购</td></tr>
  <% end %>
</table>

app/views/users/new.html.erb
<%= provide(:title, '新用户注册') %>

<div class="row">
  <div class="span6 offset3">

    <br/><h1><%= @user.investor? ? "资本方":"企业方" %>注册</h1><br/><br/>

    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "创建账号", class: "btn btn-large btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <div class="span6 offset3">

    <br/><h1><%= gravatar_for @user %> <%= @user.name %></h1><br/><br/>

    <table class="table table-striped">
      <% if @user.investor? %>
        <tr><th>资金规模</th><td>10亿</td></tr>
        <tr><th>主要兴趣</th><td>抵押贷款/PE投资/资产收购</td></tr>
      <% else %>
        <tr><th>行业</th><td>互联网与信息技术</td></tr>
        <tr><th>性质</th><td>国营企业</td></tr>
      <% end %>
    </table>

    <%= link_to "修改", edit_user_path(current_user), class: "btn pull-right" %>
  </div>
</div>